Repository JoaoGW/GuiaTuristico, pull requests merged in 2025-05, with the labels that each got.

#10 resolvido bugs na pagina login
  src/screens/Login.tsx
Labels: bug

#12 Feat/integracao ia
  src/assets/OpenAI/OpenAI-black-monoblossom.svg
  src/assets/OpenAI/OpenAI-black-wordmark.svg
  src/assets/OpenAI/OpenAI-white-monoblossom.svg
  src/assets/OpenAI/OpenAI-white-wordmark.svg
  src/components/NavigationBar.tsx
  src/pages/api/geracaoRoteiro.ts
  src/routes/auth.routes.tsx
  src/screens/GenerateItinerary.tsx
  src/utils/gptRequests.ts
  tsconfig.json
Labels: documentation, enhancement

#15 Feature: Maps & Localization
  package-lock.json
  package.json
  src/components/CurrentStatusBar.tsx
  src/components/Maps/Maps.tsx
  src/screens/GenerateItinerary.tsx
  src/screens/Home.tsx
  src/utils/requestDeviceLocation.tsx
Labels: enhancement

#16 Updated the Expo SDK version to v53.0
  package-lock.json
  package.json
Labels: enhancement

#20 Feat/user preferences
  0c2ff902d6dae50cbe67ee23d1fa9e0488221ddd
  src/assets/background2.webp
  src/assets/balada.png
  src/assets/cachoeiras.png
  src/assets/ciencias.png
  src/assets/comida.png
  src/assets/cultura.png
  src/assets/eventos.png
  src/assets/igrejas.png
  src/assets/monumentos.png
  src/assets/museu.png
  src/assets/parques.png
  src/components/Register/Tags.tsx
  src/data/tags.json
  src/routes/auth.routes.tsx
  src/screens/Login.tsx
  src/screens/UserPreferences.tsx
  src/utils/tagsLoader.ts
Labels: enhancement

#24 Feat/user preferences Funcional
  package-lock.json
  package.json
  src/components/Register/Tags.tsx
  src/routes/auth.routes.tsx
  src/screens/GenerateItinerary.tsx
  src/screens/Settings.tsx
  src/screens/UserPreferences.tsx
  src/utils/selectedTagsStore.ts
Labels: enhancement
